### ISSUE TITLE
example data

### ISSUE THREAD

**Issue by haehn** [syrousseau/qfib#2]
Hello - we love the project. Is it possible to get access to some example data? Somehow the compression rates on our data is good but looses a lot of precision. I wonder if our data is the problem. Could you please share some data that works really well with qFib? Thank you so much!

**Comment by CorentinMercier** [comment]
Hello, thank you for your interest in this project.
We think that the lost of precision might be due to the way your data is generated.
We created a new repository with some small working examples:
https://gitlab.com/comercier/qfib-data
If your data is generated with constant segment length (this is not the case with the iFOD2 algorithm from mrtrix3 for example) and the segment length is quite big (more than 0.5mm), you may want to use a 16bit quantization (-b flag).
You will also find in the table 3 of the paper (preprint.pdf) the errors you should get depending on the way the data was generated.

**Comment by haehn** [comment]
That's great - thank you very much! Do you have a description of the data? Subjects? Scanner? Tracking algorithm? Other acquisition parameters?

**Comment by syrousseau** [comment]
Hello, 
As you can see, the description of the data is in the linked repository (https://gitlab.com/comercier/qfib-data/-/blob/master/README.md) and in the paper. We got the data from the 3 Tesla scanner: https://www.humanconnectome.org/study/hcp-young-adult/document/1200-subjects-data-release
As described, the data were generated using iFOD1 and SD_STREAM tracking algorithms. 
We forced the fibers to be between 40 and 256 mm in length and forced the fibers to end on the cortical surface while staying in the white matter.
